export const encodedFeatures = JSON.stringify({
  articles_preview_enabled: true,
  c9s_tweet_anatomy_moderator_badge_enabled: true,
  communities_web_enable_tweet_community_results_fetch: true,
  creator_subscriptions_quote_tweet_preview_enabled: false,
  creator_subscriptions_tweet_preview_api_enabled: true,
  freedom_of_speech_not_reach_fetch_enabled: true,
  graphql_is_translatable_rweb_tweet_is_translatable_enabled: true,
  longform_notetweets_consumption_enabled: true,
  longform_notetweets_inline_media_enabled: true,
  longform_notetweets_rich_text_read_enabled: true,
  responsive_web_edit_tweet_api_enabled: true,
  responsive_web_enhance_cards_enabled: false,
  responsive_web_graphql_exclude_directive_enabled: true,
  responsive_web_graphql_skip_user_profile_image_extensions_enabled: false,
  responsive_web_graphql_timeline_navigation_enabled: true,
  responsive_web_twitter_article_tweet_consumption_enabled: true,
  rweb_tipjar_consumption_enabled: true,
  rweb_video_timestamps_enabled: true,
  standardized_nudges_misinfo: true,
  tweet_awards_web_tipping_enabled: false,
  tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled: true,
  tweetypie_unmention_optimization_enabled: true,
  verified_phone_label_enabled: false,
  view_counts_everywhere_api_enabled: true,
})

export const encodedFieldToggles = JSON.stringify({
  withArticlePlainText: false,
  withArticleRichContentState: true,
  withGrokAnalyze: false,
})

const defaultParams: Record<string, string> = {
  include_profile_interstitial_type: '1',
  include_blocking: '1',
  include_blocked_by: '1',
  include_followed_by: '1',
  include_want_retweets: '1',
  include_mute_edge: '1',
  include_can_dm: '1',
  include_can_media_tag: '1',
  include_ext_is_blue_verified: '1',
  include_ext_verified_type: '1',
  include_ext_profile_image_shape: '1',
  skip_status: '1',
  cards_platform: 'Web-12',
  include_cards: '1',
  include_ext_alt_text: 'true',
  include_ext_limited_action_results: 'true',
  include_quote_count: 'true',
  include_reply_count: '1',
  tweet_mode: 'extended',
  include_ext_views: 'true',
  include_entities: 'true',
  include_user_entities: 'true',
  include_ext_media_color: 'true',
  include_ext_media_availability: 'true',
  include_ext_sensitive_media_warning: 'true',
  include_ext_trusted_friends_metadata: 'true',
  send_error_codes: 'true',
  simple_quoted_tweet: 'true',
  ext: [
    'mediaStats',
    'highlightedLabel',
    'voiceInfo',
    'birdwatchPivot',
    'superFollowMetadata',
    'unmentionInfo',
    'editControl',
    'article',
  ].join(),
}

export function setDefaultParams(params: URLSearchParams): void {
  Object.entries(defaultParams).forEach(([name, value]) => params.set(name, value))
}
